### ISSUE TITLE
戦闘の仕様について

### ISSUE THREAD

**Issue by IceSword8492** [IceSword8492/unit#10]
現状の実装だと行動を選択した直後に敵の行動が終了する上、敵の特殊行動が分からないため仕様変更が必要と思われる。

**Comment by kuma240** [comment]
やれるか分からないけどやってみます

**Comment by IceSword8492** [comment]
@00547daic @pridetarou @kuma240

**Comment by IceSword8492** [comment]
戦闘画面に根性表記が欲しい

**Comment by 00547daic** [comment]
コメントアウトされてたものを外して根性があるときメッセージに表記されてるんだけど、HP横に追加の方がいい？
@IceSword8492

**Comment by IceSword8492** [comment]
根性 -> HP横
その他の敵行動 -> message (kbhitを用いた一時停止処理も追加)
@00547daic

**Comment by 00547daic** [comment]
根性表記をｈｐの横に”根性: 有or無”で表記するように追加
相手の行動後にD_DAMAGESTEPで溜め行動や受けたダメージを表記して何かのキーを押したらD_BATTLEに戻ってくるように追加

**Comment by IceSword8492** [comment]
実行してみて個人的に思ったことを書きます。

- 敵の行動表示を消すのがany keyだと操作ミスが多発したのでEnterキーのみのほうがいいかも？
- 根性表示が常に出ていると下のフロアでも今後根性持ちが出てくるのがわかってしまって面白みが半減するかも？(根性: 有 じゃなくて根性持ちが出てきたときだけ根性って表示するのはどうだろうか)

**Comment by 00547daic** [comment]
行動表示消すのはEnterだけにしておく。
根性表記自体は根性持ちだけ表示するのは良いと思うけど、根性が何かわからないとさすがにあれかなって思ってtipsにhp一定値まで減らそうって感じでつけ足してるんだけど隠すなら消した方が良いかな？

**Comment by IceSword8492** [comment]
tipsちゃんと読んでるやつだけわかるみたいな感じでもいいかも？

とりあえずEnterで消えるようにしてみた

https://github.com/IceSword8492/unit/tree/dev-sharo-proposal

**Comment by IceSword8492** [comment]
@00547daic tips読んでて思ったんだけどなんで最後だけ「。。」になってるん？
https://github.com/IceSword8492/unit/blob/853a0fcacd3af737e341c58adee82907cc7e8216/displayRule.cpp#L19

**Comment by IceSword8492** [comment]
根性表示を変更してみた

https://github.com/IceSword8492/unit/tree/dev-sharo-proposal

**Comment by 00547daic** [comment]
@IceSword8492 
。。になってるの完全に直し忘れだわ。escmenu開いた時のやつは直したんだけどruleの方直ってなかったのか…

**Comment by IceSword8492** [comment]
なるほど

dev-sharo-proposalマージしていい？

**Comment by 00547daic** [comment]
良いと思う

**Comment by IceSword8492** [comment]
#32 マージしました

一旦Closeします。問題があればReopenしてください。
