### ISSUE TITLE
根性

### ISSUE THREAD

**Issue by IceSword8492** [IceSword8492/unit#13]
根性未実装

**Comment by 00547daic** [comment]
エンカウント時typeが2or3の場合state[0]を１にしてhpが20%以下(6000,10000)になったらstate[0]を0にするようにしました

**Comment by IceSword8492** [comment]
いまって根性ついたやつも倒せる状態？

**Comment by 00547daic** [comment]
倒しきらずにhp20%以下まで削れば根性外れるからそうすれば倒せるかな一応根性発動してるのは確認した

**Comment by IceSword8492** [comment]
ラスボスを4700くらいにしてタメレポートで殴ったら25000まで回復した

**Comment by 00547daic** [comment]
根性のオンオフを自分が攻撃したあとに修正。4f裏ボスともに20%以下で根性が外れて倒せることを確認

**Comment by IceSword8492** [comment]
修正を確認しました。
Closeします。
