### ISSUE TITLE
【重要】重大なバグを発見

### ISSUE THREAD

**Issue by IceSword8492** [IceSword8492/unit#29]
developブランチのソースをビルドして実行すると、特定の条件下でゲームがクラッシュする。

## 現在確認済みのクラッシュ情報

- 裏ボスとの戦闘で何か行動をするとクラッシュ

- 通常最終ボスとの戦闘中に謎のクラッシュ

**Comment by IceSword8492** [comment]
@00547daic 以下のオプションつけて実行してテストしてみて

```sh
./a.exe --debug --set-start-postion 6 2 --set-items 100 100 1 --set-intelligence 10000
``

**Comment by 00547daic** [comment]
クラッシュしないで普通にクリアしたんだけど。
俺いつもボスのデバッグ
.\a.exe --debug --set-fps 5 --show-fps --set-start-position 6 2 --set-intelligence 8000 --set-items 2 20 1
でやってるんだけどやってること変わらんしなあ
@IceSword8492

**Comment by IceSword8492** [comment]
@00547daic 理由わかったわw

```sh
g++ ./main.cpp -lwinmm -lws2_32 -O3
```
これでコンパイルしてたせいだったわw

最適化オプションつけるだけでバグるとは思ってなかったw
