### ISSUE TITLE
バグ探し

### ISSUE THREAD

**Issue by IceSword8492** [IceSword8492/unit#31]
各自様々な操作をしてバグがないか「必ず」確認してください。

確認後はここに報告してください。

全員の報告が確認できたらversionを1.0.0 Releaseにしてmasterにマージします。

@pridetarou @00547daic @kuma240

**Comment by IceSword8492** [comment]
#33

**Comment by IceSword8492** [comment]
#34

**Comment by pridetarou** [comment]
4Fのボスの根性って何回も発動するんだっけ？

**Comment by IceSword8492** [comment]
@pridetarou 
今の実装だと根性が発動したときにHPが半分まで回復して、そのあとに根性解除の判定が行われてるね。
要するに、一回HPを1以上20%以下にしないと根性が解除されないで何度でも発動するはず！

**Comment by pridetarou** [comment]
了解
なら操作した感じバグは見当たらなかった

**Comment by IceSword8492** [comment]
了解

**Comment by 00547daic** [comment]
既出のゲームクリア、時間切れのゲームオーバーによるバグ以外には操作不可になるなどのバグは見当たらなかった。

**Comment by kuma240** [comment]
自分も操作してみた感じ問題なさそう
