### ISSUE TITLE
Author's comment is not found.

### ISSUE THREAD

**Issue by IceSword8492** [IceSword8492/unit#5]
https://github.com/IceSword8492/unit/blob/01b17ec6a6dbb723b4b159317b47e15994cddbd5/useSkill.c#L1
作成者の名前等のコメントアウトがない

**Comment by 00547daic** [comment]
fixed in https://github.com/IceSword8492/unit/commit/f08fb0d8c7e19191ab4fd39795adfce1cd92b9e4
