### ISSUE TITLE
enemy attack

### ISSUE THREAD

**Issue by 00547daic** [IceSword8492/unit#6]
こちらの攻撃で敵のhpを0にした場合でも反撃を食らう

**Comment by IceSword8492** [comment]
https://github.com/IceSword8492/unit/commit/d54c3e5232c50529a51f6c4bf18c11ac5abb04d4

直ってなかったら明日(今日)もっかいみる

**Comment by 00547daic** [comment]
8c93428
通常攻撃で倒した場合反撃されないようになっていたので、同じようにレポートアタックの部分も反撃されないように修正しました

**Comment by IceSword8492** [comment]
ﾚﾎﾟｯﾖ攻撃の方完全に忘れてたw
さんくす
